name: LAX2016
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.39916924526914954
  lightness: 0.7927734232507646
  saturation: 0.7598696295171976
  rhythmicContrast: 0.44301294698379934
purpose: []
